name: Syncs any new Items emojis to application's emojis

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
  schedule:
    - cron: "50 23 * * *" # 10 min edge case to midnight because skydata will refresh at midnight, so little leeway for emojis to update if any

jobs:
  sync_item_emojis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "23"

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Sync emojis
        run: node ./scripts/sync.items.emojis.mts
        env:
          CLIENT_ID: ${{secrets.CLIENT_ID}}
          TOKEN: ${{secrets.TOKEN}}

      - name: Open pr if hash map is updated
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

           if [ -n "$(git status --porcelain)" ]; then
            BRANCH_NAME="chore/emoji-hashmap"
            git checkout -B "$BRANCH_NAME"
            git add ./**/*.json
            git commit -m "chore: update emoji_hashmap: -->> ${{ github.event_name }}"
            git push --force origin "$BRANCH_NAME"

            # Check if a PR already exists
           if gh pr list --head "$BRANCH_NAME" --json number --jq '.[0].number' | grep -q '[0-9]'; then
            echo "ℹ️ PR for branch $BRANCH_NAME already exists."
           else
            echo "updated emoji hashmap. creating pr..."
            pr_url=$(gh pr create --base main --head "$BRANCH_NAME" --title "chore: update emoji_hashmap" --body "Update emoji hashes after emoji sync: Run type: >> ${{ github.event_name}}")
            echo "Created the following pr: ${pr_url}"
           fi
          else
           echo "ℹ️ No changes to emoji hashes"
          fi
